name: CI/CD - AdotAI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build & Test - Spring Boot
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”½ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: ğŸ“¦ Instalar dependÃªncias
        run: mvn clean install -DskipTests

      - name: ğŸ§ª Rodar Testes
        run: mvn test

      - name: ğŸ“Š Gerar RelatÃ³rio de Teste
        if: success()
        run: |
          echo "âœ… Todos os testes passaram com sucesso!"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ğŸš€ Deploy Simulado
        run: echo "dokcer compose up -d --build trab"
